# Generated by Django 3.1.5 on 2021-01-31 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentsPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_1', to='segments.segment')),
                ('segment2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_2', to='segments.segment')),
            ],
        ),
    ]
